### ISSUE TITLE
The plugin could not be compiled

### ISSUE THREAD

**Issue by Astra-520** [Pzdrs/hypixel-bedwars#3]
The plugin could not be compiled 
[error] / D: / hypbw / SRC / main / Java / me / pycrs / borders / listeners / asyncchatlistener. Java: [58,18] no symbols found

[error] symbol: Method renderer ((source, so [...] SAGE))

[error] location: variable event of type io.papermc.paper.event.player.asyncchatevent

[ERROR]

**Comment by Astra-520** [comment]
I deleted these, but an error is reported when the compilation is completed
[21:19:32 INFO]: [Bedwars] Enabling Bedwars v1.0-SNAPSHOT
[21:19:32 ERROR]: Error occurred while enabling Bedwars v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/json/JSONObject
        at me.pycrs.bedwars.entities.BedwarsMap.loadJSON(BedwarsMap.java:69) ~[?:?]
        at me.pycrs.bedwars.Bedwars.onEnable(Bedwars.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper-1.16.5-786.jar:git-Paper-520]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[paper-1.16.5-786.jar:git-Paper-520]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[paper-1.16.5-786.jar:git-Paper-520]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[paper-1.16.5-786.jar:git-Paper-520]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[paper-1.16.5-786.jar:git-Paper-520]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[paper-1.16.5-786.jar:git-Paper-520]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[paper-1.16.5-786.jar:git-Paper-520]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[paper-1.16.5-786.jar:git-Paper-520]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[paper-1.16.5-786.jar:git-Paper-520]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[paper-1.16.5-786.jar:git-Paper-520]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[paper-1.16.5-786.jar:git-Paper-520]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 12 more
[21:19:32 INFO]: [Bedwars] Disabling Bedwars v1.0-SNAPSHOT

**Comment by Pzdrs** [comment]
Weird, looks like the Jar doesn't contain the org.json library I use to parse JSON data. Try to decompile the Jar and see what is missing, I think it might be some differences in our IDE's compilation settings. I remember that I had to specify to include the library.
